#!/usr/bin/env bash
# configures server for nginx to be listening to port 80
#!/usr/bin/env bash
#Find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart
